-- Taxonomia ampla: subcategorias (e algumas especialidades) para todas as macrocategorias.
-- Idempotente (on conflict do nothing): nao altera o que ja existe nem o que o admin tiver editado.
-- Subcategorias vazias nao aparecem no sitemap e ficam noindex ate ter empresa.

-- contabilidade-e-juridico
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'contabilidade', 'Contabilidade', 110 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'contabilidade-empresarial', 'Contabilidade empresarial', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'contabilidade' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'contabilidade-para-mei-e-autonomos', 'Contabilidade para MEI e autônomos', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'contabilidade' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'contabilidade-para-profissionais-da-saude', 'Contabilidade para profissionais da saúde', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'contabilidade' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'contabilidade-digital', 'Contabilidade digital', 40 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'contabilidade' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'consultoria-fiscal-e-tributaria', 'Consultoria fiscal e tributária', 120 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'planejamento-tributario', 'Planejamento tributário', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'consultoria-fiscal-e-tributaria' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'recuperacao-de-creditos', 'Recuperação de créditos', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'consultoria-fiscal-e-tributaria' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'regularizacao-fiscal', 'Regularização fiscal', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'consultoria-fiscal-e-tributaria' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'abertura-e-regularizacao-de-empresas', 'Abertura e regularização de empresas', 130 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'departamento-pessoal-e-folha', 'Departamento pessoal e folha', 140 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'auditoria-e-pericia', 'Auditoria e perícia', 150 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'advocacia-empresarial', 'Advocacia empresarial', 160 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'contratos', 'Contratos', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'advocacia-empresarial' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'societario', 'Societário', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'advocacia-empresarial' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'recuperacao-judicial', 'Recuperação judicial', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'advocacia-empresarial' and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'mediacao-e-arbitragem', 'Mediação e arbitragem', 170 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'despachante-e-documentacao', 'Despachante e documentação', 180 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'bpo-financeiro', 'BPO financeiro', 190 from categories m where m.level = 1 and m.slug = 'contabilidade-e-juridico' on conflict do nothing;

-- direito
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'advocacia-civil', 'Advocacia civil', 110 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'advocacia-trabalhista', 'Advocacia trabalhista', 120 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'advocacia-previdenciaria', 'Advocacia previdenciária', 130 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'familia-e-sucessoes', 'Família e sucessões', 140 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'divorcio', 'Divórcio', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'familia-e-sucessoes' and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'inventario-e-heranca', 'Inventário e herança', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'familia-e-sucessoes' and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'guarda-e-pensao', 'Guarda e pensão', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'familia-e-sucessoes' and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'advocacia-criminal', 'Advocacia criminal', 150 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'direito-imobiliario', 'Direito imobiliário', 160 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'direito-do-consumidor', 'Direito do consumidor', 170 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'direito-digital-e-lgpd', 'Direito digital e LGPD', 180 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'propriedade-intelectual-e-marcas', 'Propriedade intelectual e marcas', 190 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'direito-medico-e-da-saude', 'Direito médico e da saúde', 200 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'direito-tributario', 'Direito tributário', 210 from categories m where m.level = 1 and m.slug = 'direito' on conflict do nothing;

-- saude-e-estetica
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'nutricao', 'Nutrição', 110 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'nutricao-clinica', 'Nutrição clínica', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'nutricao' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'nutricao-esportiva', 'Nutrição esportiva', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'nutricao' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'emagrecimento', 'Emagrecimento', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'nutricao' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'pediatria', 'Pediatria', 120 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'ginecologia-e-obstetricia', 'Ginecologia e obstetrícia', 130 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cardiologia', 'Cardiologia', 140 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'ortopedia', 'Ortopedia', 150 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'oftalmologia', 'Oftalmologia', 160 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'otorrinolaringologia', 'Otorrinolaringologia', 170 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'fonoaudiologia', 'Fonoaudiologia', 180 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'terapias-integrativas', 'Terapias integrativas', 190 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'acupuntura', 'Acupuntura', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'terapias-integrativas' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'massoterapia', 'Massoterapia', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'terapias-integrativas' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'reiki-e-meditacao', 'Reiki e meditação', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'terapias-integrativas' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'medicina-estetica', 'Medicina estética', 200 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'botox-e-preenchimento', 'Botox e preenchimento', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'medicina-estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'bioestimuladores', 'Bioestimuladores', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'medicina-estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'tratamento-de-cicatrizes', 'Tratamento de cicatrizes', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'medicina-estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'clinicas-de-imagem-e-exames', 'Clínicas de imagem e exames', 210 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'bem-estar-e-atividade-fisica', 'Bem-estar e atividade física', 220 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'pilates', 'Pilates', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'bem-estar-e-atividade-fisica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'personal-trainer', 'Personal trainer', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'bem-estar-e-atividade-fisica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'yoga', 'Yoga', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'bem-estar-e-atividade-fisica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'podologia', 'Podologia', 230 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'saude-mental-e-psiquiatria', 'Saúde mental e psiquiatria', 240 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'psicologia', 'Psicologia', 250 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'psicologia-clinica', 'Psicologia clínica', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'psicologia' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'neuropsicologia', 'Neuropsicologia', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'psicologia' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'terapia-de-casal-e-familia', 'Terapia de casal e família', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'psicologia' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'psicologia-infantil', 'Psicologia infantil', 40 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'psicologia' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'estetica', 'Estética', 260 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'estetica-facial', 'Estética facial', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'estetica-corporal', 'Estética corporal', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'depilacao', 'Depilação', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'micropigmentacao', 'Micropigmentação', 40 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'harmonizacao-facial', 'Harmonização facial', 50 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'estetica' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'saloes-de-beleza', 'Salões de beleza', 270 from categories m where m.level = 1 and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'cabelo', 'Cabelo', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'saloes-de-beleza' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'manicure-e-pedicure', 'Manicure e pedicure', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'saloes-de-beleza' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'maquiagem', 'Maquiagem', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'saloes-de-beleza' and m.slug = 'saude-e-estetica' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'barbearia', 'Barbearia', 40 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'saloes-de-beleza' and m.slug = 'saude-e-estetica' on conflict do nothing;

-- alimentacao
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'restaurantes', 'Restaurantes', 110 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'brasileira', 'Brasileira', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'restaurantes' and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'japonesa', 'Japonesa', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'restaurantes' and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'italiana', 'Italiana', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'restaurantes' and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'churrascaria', 'Churrascaria', 40 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'restaurantes' and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'vegetariana-e-vegana', 'Vegetariana e vegana', 50 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'restaurantes' and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cafeterias-e-padarias', 'Cafeterias e padarias', 120 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'lanchonetes-e-hamburguerias', 'Lanchonetes e hamburguerias', 130 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'pizzarias-e-massas', 'Pizzarias e massas', 140 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'confeitaria-e-doces', 'Confeitaria e doces', 150 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'marmitas-e-refeicoes', 'Marmitas e refeições', 160 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'bares-e-choperias', 'Bares e choperias', 170 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'delivery-e-dark-kitchen', 'Delivery e dark kitchen', 180 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'buffet-e-eventos', 'Buffet e eventos', 190 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'mercearias-e-emporios', 'Mercearias e empórios', 200 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'sorveterias-e-acai', 'Sorveterias e açaí', 210 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'alimentacao-saudavel', 'Alimentação saudável', 220 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'hortifruti-e-produtos-naturais', 'Hortifruti e produtos naturais', 230 from categories m where m.level = 1 and m.slug = 'alimentacao' on conflict do nothing;

-- moda-e-beleza
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'moda-feminina', 'Moda feminina', 110 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'moda-masculina', 'Moda masculina', 120 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'moda-infantil', 'Moda infantil', 130 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'calcados-e-bolsas', 'Calçados e bolsas', 140 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'joias-e-bijuterias', 'Joias e bijuterias', 150 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'oticas-e-relojoaria', 'Óticas e relojoaria', 160 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cosmeticos-e-perfumaria', 'Cosméticos e perfumaria', 170 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'moda-fitness-e-intima', 'Moda fitness e íntima', 180 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'atelie-costura-e-ajustes', 'Ateliê, costura e ajustes', 190 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'barbearias', 'Barbearias', 200 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'noivas-e-festas', 'Noivas e festas', 210 from categories m where m.level = 1 and m.slug = 'moda-e-beleza' on conflict do nothing;

-- tecnologia-e-marketing
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'marketing-digital', 'Marketing digital', 110 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'agencias-de-publicidade', 'Agências de publicidade', 120 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'redes-sociais-e-conteudo', 'Redes sociais e conteúdo', 130 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'trafego-pago-e-performance', 'Tráfego pago e performance', 140 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'sites-e-e-commerce', 'Sites e e-commerce', 150 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'desenvolvimento-de-software-e-apps', 'Desenvolvimento de software e apps', 160 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'suporte-e-consultoria-de-ti', 'Suporte e consultoria de TI', 170 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'crm-automacao-e-dados', 'CRM, automação e dados', 180 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'inteligencia-artificial', 'Inteligência artificial', 190 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'seguranca-da-informacao', 'Segurança da informação', 200 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'fotografia-e-video', 'Fotografia e vídeo', 210 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'assessoria-de-imprensa-e-relacoes-publicas', 'Assessoria de imprensa e relações públicas', 220 from categories m where m.level = 1 and m.slug = 'tecnologia-e-marketing' on conflict do nothing;

-- educacao
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'escolas-e-educacao-infantil', 'Escolas e educação infantil', 110 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'idiomas', 'Idiomas', 120 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'ingles', 'Inglês', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'idiomas' and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'espanhol', 'Espanhol', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'idiomas' and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'mandarim', 'Mandarim', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'idiomas' and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'reforco-escolar', 'Reforço escolar', 130 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cursos-profissionalizantes', 'Cursos profissionalizantes', 140 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'faculdades-e-pos-graduacao', 'Faculdades e pós-graduação', 150 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'mentoria-e-coaching', 'Mentoria e coaching', 160 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'treinamentos-corporativos', 'Treinamentos corporativos', 170 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'musica-e-artes', 'Música e artes', 180 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'concursos-e-vestibulares', 'Concursos e vestibulares', 190 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cursos-de-saude-e-estetica', 'Cursos de saúde e estética', 200 from categories m where m.level = 1 and m.slug = 'educacao' on conflict do nothing;

-- design-e-arquitetura
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'arquitetura', 'Arquitetura', 110 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'design-de-interiores', 'Design de interiores', 120 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'paisagismo', 'Paisagismo', 130 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'engenharia-civil', 'Engenharia civil', 140 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'design-grafico-e-identidade-visual', 'Design gráfico e identidade visual', 150 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'marcenaria-e-moveis-planejados', 'Marcenaria e móveis planejados', 160 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'reformas-e-construcao', 'Reformas e construção', 170 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'decoracao-e-iluminacao', 'Decoração e iluminação', 180 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'design-de-produto', 'Design de produto', 190 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'maquetes-e-renderizacao-3d', 'Maquetes e renderização 3D', 200 from categories m where m.level = 1 and m.slug = 'design-e-arquitetura' on conflict do nothing;

-- investimentos
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'assessoria-de-investimentos', 'Assessoria de investimentos', 110 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'corretoras-e-bancos', 'Corretoras e bancos', 120 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'planejamento-financeiro', 'Planejamento financeiro', 130 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'seguros', 'Seguros', 140 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'seguro-de-vida', 'Seguro de vida', 10 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'seguros' and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'seguro-empresarial', 'Seguro empresarial', 20 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'seguros' and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select s.id, 3, 'seguro-saude', 'Seguro saúde', 30 from categories s join categories m on m.id = s.parent_id where s.level = 2 and s.slug = 'seguros' and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'previdencia-privada', 'Previdência privada', 150 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'credito-e-consorcio', 'Crédito e consórcio', 160 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'cambio-e-comercio-exterior', 'Câmbio e comércio exterior', 170 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'gestao-patrimonial', 'Gestão patrimonial', 180 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'investimentos-imobiliarios', 'Investimentos imobiliários', 190 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'criptoativos', 'Criptoativos', 200 from categories m where m.level = 1 and m.slug = 'investimentos' on conflict do nothing;

-- laboratorio
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'analises-clinicas', 'Análises clínicas', 110 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'diagnostico-por-imagem', 'Diagnóstico por imagem', 120 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'laboratorio-odontologico', 'Laboratório odontológico', 130 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'anatomia-patologica', 'Anatomia patológica', 140 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'genetica-e-medicina-diagnostica', 'Genética e medicina diagnóstica', 150 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'exames-ocupacionais', 'Exames ocupacionais', 160 from categories m where m.level = 1 and m.slug = 'laboratorio' on conflict do nothing;

-- outros
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'servicos-para-empresas', 'Serviços para empresas', 110 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'coworking-e-escritorios-virtuais', 'Coworking e escritórios virtuais', 120 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'recursos-humanos-e-recrutamento', 'Recursos humanos e recrutamento', 130 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'consultoria-de-negocios', 'Consultoria de negócios', 140 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'eventos-e-cerimonial', 'Eventos e cerimonial', 150 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'graficas-e-papelaria', 'Gráficas e papelaria', 160 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'transporte-e-logistica', 'Transporte e logística', 170 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'limpeza-e-conservacao', 'Limpeza e conservação', 180 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'seguranca-e-monitoramento', 'Segurança e monitoramento', 190 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'pet-shops-e-veterinaria', 'Pet shops e veterinária', 200 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'turismo-e-viagens', 'Turismo e viagens', 210 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'traducao-e-idiomas-corporativos', 'Tradução e idiomas corporativos', 220 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'associacoes-e-instituicoes', 'Associações e instituições', 230 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
insert into categories (parent_id, level, slug, name, sort_order) select m.id, 2, 'manutencao-e-assistencia-tecnica', 'Manutenção e assistência técnica', 240 from categories m where m.level = 1 and m.slug = 'outros' on conflict do nothing;
