-- Palavras-chave (sinonimos) das categorias para a pesquisa inteligente. Editaveis no banco.
-- Ex.: quem digita "odontologia" ou "aparelho" encontra Dentistas. A busca ainda tolera erro de digitacao e plural.
alter table categories add column if not exists keywords text[] not null default '{}';

update categories set keywords = (select array(select distinct unnest(keywords || array['saude', 'medico', 'clinica', 'bem estar']))) where slug = 'saude-e-estetica';
update categories set keywords = (select array(select distinct unnest(keywords || array['contador', 'advogado', 'juridico', 'impostos']))) where slug = 'contabilidade-e-juridico';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado', 'advogada', 'advocacia', 'juridico', 'processo', 'justica']))) where slug = 'direito';
update categories set keywords = (select array(select distinct unnest(keywords || array['comida', 'comer', 'almoco', 'jantar', 'lanche', 'fome']))) where slug = 'alimentacao';
update categories set keywords = (select array(select distinct unnest(keywords || array['roupa', 'roupas', 'estilo', 'beleza']))) where slug = 'moda-e-beleza';
update categories set keywords = (select array(select distinct unnest(keywords || array['tecnologia', 'marketing', 'digital', 'ti']))) where slug = 'tecnologia-e-marketing';
update categories set keywords = (select array(select distinct unnest(keywords || array['curso', 'cursos', 'aula', 'aulas', 'escola', 'estudar']))) where slug = 'educacao';
update categories set keywords = (select array(select distinct unnest(keywords || array['design', 'arquiteto', 'projeto', 'obra']))) where slug = 'design-e-arquitetura';
update categories set keywords = (select array(select distinct unnest(keywords || array['investir', 'dinheiro', 'financeiro', 'patrimonio']))) where slug = 'investimentos';
update categories set keywords = (select array(select distinct unnest(keywords || array['exame', 'exames', 'laboratorial']))) where slug = 'laboratorio';
update categories set keywords = (select array(select distinct unnest(keywords || array['servicos']))) where slug = 'outros';
update categories set keywords = (select array(select distinct unnest(keywords || array['dentista', 'odontologia', 'odontologo', 'odontologico', 'dentes', 'dente', 'sorriso', 'clinica odontologica', 'ortodontista', 'implantodontista']))) where slug = 'dentistas';
update categories set keywords = (select array(select distinct unnest(keywords || array['limpeza dental', 'canal', 'restauracao', 'consulta odontologica']))) where slug = 'clinica-geral';
update categories set keywords = (select array(select distinct unnest(keywords || array['aparelho', 'aparelho dentario', 'aparelho ortodontico', 'invisalign', 'alinhador']))) where slug = 'ortodontia';
update categories set keywords = (select array(select distinct unnest(keywords || array['implante dentario', 'implante', 'protese', 'protocolo']))) where slug = 'implantes';
update categories set keywords = (select array(select distinct unnest(keywords || array['harmonizacao facial', 'botox', 'preenchimento', 'labios']))) where slug = 'harmonizacao-orofacial';
update categories set keywords = (select array(select distinct unnest(keywords || array['dentista infantil', 'dentista de crianca', 'odontologia infantil']))) where slug = 'odontopediatria';
update categories set keywords = (select array(select distinct unnest(keywords || array['tratamento de canal', 'canal', 'endodontista']))) where slug = 'endodontia';
update categories set keywords = (select array(select distinct unnest(keywords || array['gengiva', 'periodontista']))) where slug = 'periodontia';
update categories set keywords = (select array(select distinct unnest(keywords || array['medico', 'medica', 'consulta', 'clinica geral', 'check up', 'clinico geral']))) where slug = 'clinicas-medicas';
update categories set keywords = (select array(select distinct unnest(keywords || array['dermatologista', 'pele', 'acne', 'manchas', 'dermato']))) where slug = 'dermatologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['psicologo', 'psicologa', 'terapia', 'terapeuta', 'ansiedade', 'saude mental']))) where slug = 'psicologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['fisioterapeuta', 'reabilitacao', 'rpg', 'dor nas costas', 'lesao']))) where slug = 'fisioterapia';
update categories set keywords = (select array(select distinct unnest(keywords || array['esteticista', 'limpeza de pele', 'tratamento facial', 'tratamento corporal', 'estetica avancada', 'regenerativa']))) where slug = 'estetica';
update categories set keywords = (select array(select distinct unnest(keywords || array['salao', 'cabeleireiro', 'cabeleireira', 'cabelo', 'escova', 'coloracao', 'corte', 'hair', 'unha', 'unhas']))) where slug = 'saloes-de-beleza';
update categories set keywords = (select array(select distinct unnest(keywords || array['laboratorio', 'exame de sangue', 'exames laboratoriais', 'analises']))) where slug = 'laboratorios';
update categories set keywords = (select array(select distinct unnest(keywords || array['nutricionista', 'dieta', 'emagrecer', 'emagrecimento', 'reeducacao alimentar']))) where slug = 'nutricao';
update categories set keywords = (select array(select distinct unnest(keywords || array['pediatra', 'crianca', 'bebe', 'infantil']))) where slug = 'pediatria';
update categories set keywords = (select array(select distinct unnest(keywords || array['ginecologista', 'obstetra', 'gestante', 'pre natal']))) where slug = 'ginecologia-e-obstetricia';
update categories set keywords = (select array(select distinct unnest(keywords || array['cardiologista', 'coracao', 'pressao']))) where slug = 'cardiologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['ortopedista', 'coluna', 'joelho', 'ombro']))) where slug = 'ortopedia';
update categories set keywords = (select array(select distinct unnest(keywords || array['oftalmologista', 'oculista', 'oculos', 'vista', 'visao']))) where slug = 'oftalmologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['otorrino', 'otorrinolaringologista', 'ouvido', 'garganta', 'nariz']))) where slug = 'otorrinolaringologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['fonoaudiologo', 'fonoaudiologa', 'fala', 'audicao']))) where slug = 'fonoaudiologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['acupuntura', 'massagem', 'reiki', 'holistica', 'meditacao']))) where slug = 'terapias-integrativas';
update categories set keywords = (select array(select distinct unnest(keywords || array['botox', 'preenchimento', 'bioestimulador', 'rejuvenescimento']))) where slug = 'medicina-estetica';
update categories set keywords = (select array(select distinct unnest(keywords || array['ultrassom', 'ressonancia', 'tomografia', 'raio x', 'mamografia']))) where slug = 'clinicas-de-imagem-e-exames';
update categories set keywords = (select array(select distinct unnest(keywords || array['academia', 'treino', 'pilates', 'yoga', 'personal', 'ginastica']))) where slug = 'bem-estar-e-atividade-fisica';
update categories set keywords = (select array(select distinct unnest(keywords || array['podologo', 'pe', 'unha encravada', 'calo']))) where slug = 'podologia';
update categories set keywords = (select array(select distinct unnest(keywords || array['psiquiatra', 'depressao', 'ansiedade']))) where slug = 'saude-mental-e-psiquiatria';
update categories set keywords = (select array(select distinct unnest(keywords || array['contador', 'contadora', 'contabil', 'imposto de renda', 'irpf', 'declaracao', 'abrir empresa', 'mei', 'balanco']))) where slug = 'contabilidade';
update categories set keywords = (select array(select distinct unnest(keywords || array['contador empresarial', 'escrita fiscal']))) where slug = 'contabilidade-empresarial';
update categories set keywords = (select array(select distinct unnest(keywords || array['mei', 'microempreendedor', 'autonomo', 'cnpj']))) where slug = 'contabilidade-para-mei-e-autonomos';
update categories set keywords = (select array(select distinct unnest(keywords || array['tributario', 'imposto', 'impostos', 'tributos', 'planejamento tributario']))) where slug = 'consultoria-fiscal-e-tributaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['abrir empresa', 'abrir cnpj', 'registro de empresa', 'junta comercial', 'alvara']))) where slug = 'abertura-e-regularizacao-de-empresas';
update categories set keywords = (select array(select distinct unnest(keywords || array['folha de pagamento', 'funcionarios', 'rh', 'admissao', 'esocial']))) where slug = 'departamento-pessoal-e-folha';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado empresarial', 'contratos', 'societario']))) where slug = 'advocacia-empresarial';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado civil', 'indenizacao', 'cobranca']))) where slug = 'advocacia-civil';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado trabalhista', 'demissao', 'rescisao', 'horas extras', 'direitos do trabalhador']))) where slug = 'advocacia-trabalhista';
update categories set keywords = (select array(select distinct unnest(keywords || array['aposentadoria', 'inss', 'beneficio', 'previdenciario']))) where slug = 'advocacia-previdenciaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['divorcio', 'inventario', 'heranca', 'pensao', 'guarda', 'testamento']))) where slug = 'familia-e-sucessoes';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado criminal', 'defesa criminal']))) where slug = 'advocacia-criminal';
update categories set keywords = (select array(select distinct unnest(keywords || array['advogado imobiliario', 'usucapiao', 'contrato de aluguel', 'escritura']))) where slug = 'direito-imobiliario';
update categories set keywords = (select array(select distinct unnest(keywords || array['consumidor', 'procon', 'reclamacao']))) where slug = 'direito-do-consumidor';
update categories set keywords = (select array(select distinct unnest(keywords || array['lgpd', 'privacidade', 'protecao de dados', 'crimes digitais']))) where slug = 'direito-digital-e-lgpd';
update categories set keywords = (select array(select distinct unnest(keywords || array['registrar marca', 'inpi', 'patente', 'direitos autorais']))) where slug = 'propriedade-intelectual-e-marcas';
update categories set keywords = (select array(select distinct unnest(keywords || array['plano de saude', 'erro medico', 'negativa de cobertura']))) where slug = 'direito-medico-e-da-saude';
update categories set keywords = (select array(select distinct unnest(keywords || array['restaurante', 'almoco', 'jantar', 'comida', 'refeicao', 'prato feito']))) where slug = 'restaurantes';
update categories set keywords = (select array(select distinct unnest(keywords || array['cafe', 'padaria', 'pao', 'cafeteria', 'lanche da tarde']))) where slug = 'cafeterias-e-padarias';
update categories set keywords = (select array(select distinct unnest(keywords || array['lanche', 'hamburguer', 'burger', 'salgado', 'lanchonete']))) where slug = 'lanchonetes-e-hamburguerias';
update categories set keywords = (select array(select distinct unnest(keywords || array['pizza', 'pizzaria', 'macarrao', 'massa']))) where slug = 'pizzarias-e-massas';
update categories set keywords = (select array(select distinct unnest(keywords || array['bolo', 'bolos', 'doce', 'doces', 'brigadeiro', 'torta', 'confeiteira', 'cupcake']))) where slug = 'confeitaria-e-doces';
update categories set keywords = (select array(select distinct unnest(keywords || array['marmita', 'marmitex', 'quentinha', 'almoco executivo']))) where slug = 'marmitas-e-refeicoes';
update categories set keywords = (select array(select distinct unnest(keywords || array['bar', 'cerveja', 'chopp', 'happy hour', 'drinks']))) where slug = 'bares-e-choperias';
update categories set keywords = (select array(select distinct unnest(keywords || array['delivery', 'entrega', 'dark kitchen', 'ifood']))) where slug = 'delivery-e-dark-kitchen';
update categories set keywords = (select array(select distinct unnest(keywords || array['buffet', 'festa', 'coffee break', 'salgadinhos']))) where slug = 'buffet-e-eventos';
update categories set keywords = (select array(select distinct unnest(keywords || array['mercado', 'emporio', 'mercearia', 'empório']))) where slug = 'mercearias-e-emporios';
update categories set keywords = (select array(select distinct unnest(keywords || array['sorvete', 'acai', 'picole', 'gelato']))) where slug = 'sorveterias-e-acai';
update categories set keywords = (select array(select distinct unnest(keywords || array['saudavel', 'fit', 'vegano', 'vegetariano', 'natural', 'sem gluten']))) where slug = 'alimentacao-saudavel';
update categories set keywords = (select array(select distinct unnest(keywords || array['roupa feminina', 'vestido', 'blusa', 'boutique']))) where slug = 'moda-feminina';
update categories set keywords = (select array(select distinct unnest(keywords || array['roupa masculina', 'camisa', 'terno', 'alfaiataria']))) where slug = 'moda-masculina';
update categories set keywords = (select array(select distinct unnest(keywords || array['sapato', 'tenis', 'sandalia', 'bolsa', 'mochila']))) where slug = 'calcados-e-bolsas';
update categories set keywords = (select array(select distinct unnest(keywords || array['joia', 'joias', 'bijuteria', 'anel', 'alianca', 'semijoia']))) where slug = 'joias-e-bijuterias';
update categories set keywords = (select array(select distinct unnest(keywords || array['oculos', 'otica', 'lente', 'relogio']))) where slug = 'oticas-e-relojoaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['perfume', 'maquiagem', 'cosmetico', 'skincare']))) where slug = 'cosmeticos-e-perfumaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['barbeiro', 'barba', 'corte masculino']))) where slug = 'barbearias';
update categories set keywords = (select array(select distinct unnest(keywords || array['vestido de noiva', 'noiva', 'festa', 'madrinha']))) where slug = 'noivas-e-festas';
update categories set keywords = (select array(select distinct unnest(keywords || array['marketing', 'anuncios', 'google ads', 'meta ads', 'divulgar', 'divulgacao', 'seo']))) where slug = 'marketing-digital';
update categories set keywords = (select array(select distinct unnest(keywords || array['agencia', 'publicidade', 'propaganda', 'campanha']))) where slug = 'agencias-de-publicidade';
update categories set keywords = (select array(select distinct unnest(keywords || array['social media', 'instagram', 'facebook', 'tiktok', 'conteudo', 'posts']))) where slug = 'redes-sociais-e-conteudo';
update categories set keywords = (select array(select distinct unnest(keywords || array['trafego', 'anuncio', 'google ads', 'facebook ads', 'performance']))) where slug = 'trafego-pago-e-performance';
update categories set keywords = (select array(select distinct unnest(keywords || array['site', 'sites', 'loja virtual', 'landing page', 'pagina web', 'ecommerce', 'criar site']))) where slug = 'sites-e-e-commerce';
update categories set keywords = (select array(select distinct unnest(keywords || array['sistema', 'aplicativo', 'app', 'programador', 'software', 'desenvolvedor']))) where slug = 'desenvolvimento-de-software-e-apps';
update categories set keywords = (select array(select distinct unnest(keywords || array['computador', 'informatica', 'ti', 'suporte tecnico', 'rede', 'servidor']))) where slug = 'suporte-e-consultoria-de-ti';
update categories set keywords = (select array(select distinct unnest(keywords || array['crm', 'automacao', 'dados', 'dashboard', 'planilha']))) where slug = 'crm-automacao-e-dados';
update categories set keywords = (select array(select distinct unnest(keywords || array['ia', 'ai', 'chatbot', 'automacao com ia']))) where slug = 'inteligencia-artificial';
update categories set keywords = (select array(select distinct unnest(keywords || array['ciberseguranca', 'antivirus', 'backup', 'lgpd']))) where slug = 'seguranca-da-informacao';
update categories set keywords = (select array(select distinct unnest(keywords || array['fotografo', 'fotografia', 'ensaio', 'video', 'filmagem', 'foto']))) where slug = 'fotografia-e-video';
update categories set keywords = (select array(select distinct unnest(keywords || array['ingles', 'espanhol', 'frances', 'curso de idiomas', 'escola de ingles', 'lingua']))) where slug = 'idiomas';
update categories set keywords = (select array(select distinct unnest(keywords || array['aula particular', 'professor particular', 'reforco']))) where slug = 'reforco-escolar';
update categories set keywords = (select array(select distinct unnest(keywords || array['coach', 'coaching', 'mentor', 'desenvolvimento pessoal']))) where slug = 'mentoria-e-coaching';
update categories set keywords = (select array(select distinct unnest(keywords || array['treinamento', 'capacitacao', 'palestra', 'workshop']))) where slug = 'treinamentos-corporativos';
update categories set keywords = (select array(select distinct unnest(keywords || array['musica', 'violao', 'piano', 'canto', 'arte', 'desenho']))) where slug = 'musica-e-artes';
update categories set keywords = (select array(select distinct unnest(keywords || array['concurso', 'vestibular', 'enem', 'preparatorio']))) where slug = 'concursos-e-vestibulares';
update categories set keywords = (select array(select distinct unnest(keywords || array['arquiteto', 'arquiteta', 'projeto arquitetonico', 'planta', 'aprovacao de projeto']))) where slug = 'arquitetura';
update categories set keywords = (select array(select distinct unnest(keywords || array['decoracao', 'decorador', 'interiores', 'ambientes']))) where slug = 'design-de-interiores';
update categories set keywords = (select array(select distinct unnest(keywords || array['jardim', 'jardinagem', 'paisagista']))) where slug = 'paisagismo';
update categories set keywords = (select array(select distinct unnest(keywords || array['engenheiro', 'engenheira', 'obra', 'laudo', 'calculo estrutural']))) where slug = 'engenharia-civil';
update categories set keywords = (select array(select distinct unnest(keywords || array['logo', 'logotipo', 'marca', 'identidade visual', 'designer']))) where slug = 'design-grafico-e-identidade-visual';
update categories set keywords = (select array(select distinct unnest(keywords || array['moveis', 'marceneiro', 'armario', 'planejados', 'sob medida']))) where slug = 'marcenaria-e-moveis-planejados';
update categories set keywords = (select array(select distinct unnest(keywords || array['reforma', 'construcao', 'pedreiro', 'obra', 'construtora']))) where slug = 'reformas-e-construcao';
update categories set keywords = (select array(select distinct unnest(keywords || array['luminaria', 'iluminacao', 'decoracao']))) where slug = 'decoracao-e-iluminacao';
update categories set keywords = (select array(select distinct unnest(keywords || array['assessor', 'investir', 'renda fixa', 'acoes', 'bolsa', 'tesouro']))) where slug = 'assessoria-de-investimentos';
update categories set keywords = (select array(select distinct unnest(keywords || array['corretora', 'banco', 'conta']))) where slug = 'corretoras-e-bancos';
update categories set keywords = (select array(select distinct unnest(keywords || array['planejador', 'organizar financas', 'aposentadoria', 'reserva de emergencia']))) where slug = 'planejamento-financeiro';
update categories set keywords = (select array(select distinct unnest(keywords || array['seguro', 'corretor de seguros', 'seguro auto', 'seguro residencial']))) where slug = 'seguros';
update categories set keywords = (select array(select distinct unnest(keywords || array['previdencia', 'pgbl', 'vgbl']))) where slug = 'previdencia-privada';
update categories set keywords = (select array(select distinct unnest(keywords || array['emprestimo', 'financiamento', 'consorcio', 'credito', 'capital de giro']))) where slug = 'credito-e-consorcio';
update categories set keywords = (select array(select distinct unnest(keywords || array['cambio', 'dolar', 'importacao', 'exportacao']))) where slug = 'cambio-e-comercio-exterior';
update categories set keywords = (select array(select distinct unnest(keywords || array['bitcoin', 'cripto', 'criptomoeda']))) where slug = 'criptoativos';
update categories set keywords = (select array(select distinct unnest(keywords || array['exame de sangue', 'exame de urina', 'hemograma', 'laboratorio']))) where slug = 'analises-clinicas';
update categories set keywords = (select array(select distinct unnest(keywords || array['raio x', 'ultrassom', 'ressonancia', 'tomografia']))) where slug = 'diagnostico-por-imagem';
update categories set keywords = (select array(select distinct unnest(keywords || array['protese dentaria', 'protetico', 'laboratorio de protese']))) where slug = 'laboratorio-odontologico';
update categories set keywords = (select array(select distinct unnest(keywords || array['exame admissional', 'aso', 'medicina do trabalho', 'periodico']))) where slug = 'exames-ocupacionais';
update categories set keywords = (select array(select distinct unnest(keywords || array['coworking', 'sala comercial', 'escritorio', 'sala compartilhada', 'alugar sala', 'endereco fiscal']))) where slug = 'coworking-e-escritorios-virtuais';
update categories set keywords = (select array(select distinct unnest(keywords || array['rh', 'recrutamento', 'selecao', 'vagas', 'headhunter']))) where slug = 'recursos-humanos-e-recrutamento';
update categories set keywords = (select array(select distinct unnest(keywords || array['consultor', 'consultoria', 'gestao', 'estrategia']))) where slug = 'consultoria-de-negocios';
update categories set keywords = (select array(select distinct unnest(keywords || array['festa', 'casamento', 'formatura', 'cerimonialista', 'evento']))) where slug = 'eventos-e-cerimonial';
update categories set keywords = (select array(select distinct unnest(keywords || array['grafica', 'impressao', 'cartao de visita', 'banner', 'adesivo', 'papelaria']))) where slug = 'graficas-e-papelaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['frete', 'mudanca', 'motoboy', 'entrega', 'transportadora']))) where slug = 'transporte-e-logistica';
update categories set keywords = (select array(select distinct unnest(keywords || array['limpeza', 'faxina', 'diarista', 'conservacao']))) where slug = 'limpeza-e-conservacao';
update categories set keywords = (select array(select distinct unnest(keywords || array['alarme', 'camera', 'cftv', 'portaria', 'vigilancia']))) where slug = 'seguranca-e-monitoramento';
update categories set keywords = (select array(select distinct unnest(keywords || array['pet', 'pet shop', 'cachorro', 'gato', 'veterinario', 'banho e tosa', 'racao']))) where slug = 'pet-shops-e-veterinaria';
update categories set keywords = (select array(select distinct unnest(keywords || array['viagem', 'viagens', 'passagem', 'pacote', 'agencia de viagens', 'turismo']))) where slug = 'turismo-e-viagens';
update categories set keywords = (select array(select distinct unnest(keywords || array['traducao', 'tradutor', 'juramentada', 'versao']))) where slug = 'traducao-e-idiomas-corporativos';
update categories set keywords = (select array(select distinct unnest(keywords || array['associacao', 'sindicato', 'ong', 'instituicao']))) where slug = 'associacoes-e-instituicoes';
update categories set keywords = (select array(select distinct unnest(keywords || array['conserto', 'manutencao', 'assistencia tecnica', 'reparo']))) where slug = 'manutencao-e-assistencia-tecnica';

-- Frases completas que as pessoas digitam (a frase inteira precisa casar para a busca nao deixar palavra sobrando).
update categories set keywords = (select array(select distinct unnest(keywords || array['salao de beleza', 'salao de cabelo', 'cabeleireiro', 'cabeleireira']))) where slug = 'saloes-de-beleza';
update categories set keywords = (select array(select distinct unnest(keywords || array['clinica de estetica', 'centro de estetica', 'estetica avancada']))) where slug = 'estetica';
update categories set keywords = (select array(select distinct unnest(keywords || array['escritorio de contabilidade', 'empresa de contabilidade']))) where slug = 'contabilidade';
update categories set keywords = (select array(select distinct unnest(keywords || array['escritorio de advocacia', 'advogado de familia']))) where slug in ('advocacia-civil', 'familia-e-sucessoes');
